version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: onprem_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: onprem_db
      MYSQL_USER: onprem_user
      MYSQL_PASSWORD: onprem_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql_flask_app

    container_name: flask_app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"

volumes:
  mysql_data:
